### ISSUE TITLE
Passing  commenter_plan_path doesn't work

### ISSUE THREAD

**Issue by timdittler** [GetTerminus/terraform-pr-commenter#34]
TERRAFORM_VERSION: 1.5.1

I'm trying to pass a tf_plan as described in the README, but the commenter ignores the file

```
      - name: Terraform Plan
        id: plan
        run: terraform plan -refresh=true -detailed-exitcode -input=false |& tee tf_plan

      - name: Debug
        run: cat tf_plan

      - name: Comment Plan
        uses: GetTerminus/terraform-pr-commenter@v3.0.3
        with:
          commenter_type: plan
          commenter_plan_path: tf_plan
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
        env:
          EXPAND_SUMMARY_DETAILS: true
          TF_IN_AUTOMATION: true
          COMMENTER_DEBUG: true
```

Run:
```
DEBUG: COMMAND: plan
DEBUG: EXIT_CODE: 2
DEBUG: COMMENTER_INPUT: 
INFO: Found no tfplan file. Using input argument.
```
But the file is present in the debug step.
