### ISSUE TITLE
When running matrix for multiple environment the commenter only work for one environment

### ISSUE THREAD

**Issue by RamBNarayanan** [GetTerminus/terraform-pr-commenter#35]
Hi

I am using the commenter to add comments for multiple environment with a PR. But this is only adding comment for the first environment when running a matrix in parallel.

```
- uses: GetTerminus/terraform-pr-commenter@v3
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TF_WORKSPACE: ${{ inputs.environment }}
      with:
        commenter_type: plan
        commenter_plan_path: ${{ inputs.tf_directory }}/tf_plan_${{ inputs.environment }}.txt
        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
```

matrix details
```
strategy:
      max-parallel: 4
      matrix:
        environment: [dev,prd]
```
both  dev and prod has run but only dev comments are added

![image](https://github.com/GetTerminus/terraform-pr-commenter/assets/94369522/ee17438d-e09a-4a92-a12d-1e0ef55c4052)

### Dev Run details below
------------------------------
Run docker run \
INFO: Found commenter plan file.
INFO: Found 1 page(s) of comments at https://api.github.com/repos/LiberisFinance/Liberis.Quote.Api/issues/493/comments?per_page=100.
INFO: Looking for an existing plan PR comment.
INFO: No existing plan PR comment found.
INFO: Found 1 page(s) of comments at https://api.github.com/repos/LiberisFinance/Liberis.Quote.Api/issues/493/comments?per_page=100.
INFO: Looking for an existing outputs PR comment.
INFO: No existing outputs PR comment found.
INFO: Writing 1 plan comment(s)
INFO: Adding plan comment to PR.
INFO: Writing 0 outputs comment(s)

### Prd Run details below
------------------------------
Run docker run \
INFO: Found commenter plan file.
INFO: Found 1 page(s) of comments at https://api.github.com/repos/LiberisFinance/Liberis.Quote.Api/issues/493/comments?per_page=100.
INFO: Looking for an existing plan PR comment.
INFO: No existing plan PR comment found.
INFO: Found 1 page(s) of comments at https://api.github.com/repos/LiberisFinance/Liberis.Quote.Api/issues/493/comments?per_page=100.
INFO: Looking for an existing outputs PR comment.
INFO: No existing outputs PR comment found.
INFO: Writing 0 plan comment(s)
INFO: Writing 0 outputs comment(s)
