### ISSUE TITLE
Error in plan comment example in README

### ISSUE THREAD

**Issue by mikeyjarvis19** [GetTerminus/terraform-pr-commenter#41]
Just raising this because I *think* there's a mistake in the README example for the TF plan commenting. The example is currently:
```
    - uses: GetTerminus/terraform-pr-commenter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      with:
        commenter_type: plan
        commenter_plan_path: tf_plan.txt
        commenter_exitcode: ${{ steps.plan.outputs.exit }}
```

But this was giving me the error:
```
ERROR: There must be an exit code from a previous step.
```

I noticed the other examples used `exitcode` instead of `exit`, so I tried changing to that, which fixed it. E.g.:
```
    - uses: GetTerminus/terraform-pr-commenter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      with:
        commenter_type: plan
        commenter_plan_path: tf_plan.txt
        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
```

Does the example in the README just need updating?
